### ISSUE TITLE
Bulleted list styles modifier

### ISSUE THREAD

**Issue by rowlando** [sky-uk/toolkit-core#98]
We have a design requirement to render bulleted lists and the [toolkit list styles](http://sky-uk.github.io/toolkit/#core-lists) currently do not support any bullet styles. Would this be a good candidate for a modifier for list style that could be consistent across all sites? We are currently rendering it on our project using a modifier on bare list object:

```scss
.o-list-bare--disc {
  list-style: disc;
}
```

**Comment by joebell93** [comment]
By default, any list HTML markup without a modifier class should display bullets, e.g:
```
<ul>
  <li>Item 1</li>
  <li>Item 2</li>
</ul>
```

**Comment by rowlando** [comment]
Sure. Makes sense.

**Comment by luca-baldelli2** [comment]
@joebell93 The masthead currently disables list-styles globally:
```css
/* in responsive-12.css */

media="(min-width: 768px)"
#skycom-footer ol, #skycom-footer ul, 
#skycom-masthead-subnav ol #skycom-masthead-wrapper ol, 
#skycom-masthead-subnav ul, #skycom-masthead-wrapper ul, 
ol, ul {
    margin: 0;
    padding: 0;
    list-style: none;
}
```

Should there be something in `defence` files to reset list-styles in vanilla ul/ol elements?
